
services:
  tests:
    build:
      context: ../ 
      dockerfile: Tests/Dockerfile 
    environment:
      - USE_REDIS=true
      - ConnectionStrings__Redis=redis-test:6379
      - ConnectionStrings__PostgresTransaction=Host=postgres-test;Port=5432;Database=greg_company_test;Username=postgres;Password=postgres;
      - ConnectionStrings__PostgresSession=Host=postgres-test;Port=5432;Database=greg_company_test;Username=postgres;Password=postgres;
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_started

  postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greg_company_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: "redis:alpine"
