
services:
  tests:
    build:
      context: ../ 
      dockerfile: Tests/Dockerfile 
    environment:
      - USE_REDIS=true
      - ConnectionStrings__Redis=redis-test:6379
      - ConnectionStrings__DefaultConnection=Server=mssql-test;Database=TestDb;User Id=sa;Password=TestPassword123!;TrustServerCertificate=True;
    depends_on:
      mongodb-test:
        condition: service_healthy
      redis-test:
        condition: service_started

  mongodb-test:
    image: mongo:latest
    ports:
      - "27018:27018"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: "redis:alpine"
