# ==========================================================
# GREG COMPANY - INFRASTRUCTURE ORCHESTRATION (V2.1)
# Stack: .NET Core | React | SQL Server | MongoDB | Redis | Nginx
# Modo: Hybrid (Secure by default / Dev ready)
# ==========================================================

services:

  # --- [ INFRASTRUCTURE LAYER ] ---

  mongodb:
    image: mongo:latest
    container_name: mongodb-store
    volumes:
      - mongo-data:/data/db
    networks:
      - greg-network
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis-cache
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - greg-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - greg-network
    restart: always

  # --- [ GATEWAY PROXY LAYER ] ---

  proxy-gateway:
    image: nginx:alpine
    container_name: proxy-gateway
    ports:
      - "80:80" # Única porta pública de entrada do ecossistema inteiro!
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Injeta as regras do porteiro
    depends_on:
      - frontend-portal
      - frontend-admin
      - backend
    networks:
      - greg-network
    restart: always

  # --- [ APPLICATION LAYER ] ---

  backend:
    container_name: backend-api
    build: 
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - "8080" # Fechado para fora, acessível apenas pelo Nginx internamente
    env_file:
      - ../.env
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__MongoConnection=${ConnectionStrings__MongoConnection}
      - MongoDb__DatabaseName=${MONGO_DATABASE_NAME}
      - MongoDb__WriteConcern=${MONGO_WRITE_CONCERN}
      - MongoDb__Journal=${MONGO_JOURNAL}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672/
      - MercadoPago__AccessToken=${MercadoPago__AccessToken}
      - MercadoPago__WebhookSecret=${MercadoPago__WebhookSecret}
      - MercadoPago__PublicKey=${MercadoPago__PublicKey}
      - Jwt__Key=${Jwt__Key}
      - Google__ClientId=${Google__ClientId}
      - Google__ClientSecret=${Google__ClientSecret}
      - SendGrid__ApiKey=${SendGrid__ApiKey}
      - SendGrid__FromEmail=${SendGrid__FromEmail}
      - SendGrid__FromName=${SendGrid__FromName}
      - General__BaseUrl=${GENERAL__BASEURL}
      - USE_REDIS=${USE_REDIS}
    depends_on:
      redis:
        condition: service_started
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - greg-network
    volumes:
      - ../uploads:/app/wwwroot/uploads
      - ../logs:/app/logs    

  backend-worker:
    container_name: backend-worker
    build: 
      context: ../backend-worker
      dockerfile: Dockerfile
    expose:
      - "8080" # Fechado para fora, acessível apenas pelo Nginx internamente
    env_file:
      - ../.env
    environment:
      - ConnectionStrings__MongoConnection=${ConnectionStrings__MongoConnection}
      - MongoDb__DatabaseName=${MONGO_DATABASE_NAME}
      - MongoDb__WriteConcern=${MONGO_WRITE_CONCERN}
      - MongoDb__Journal=${MONGO_JOURNAL}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672/
      - SendGrid__ApiKey=${SendGrid__ApiKey}
      - SendGrid__FromEmail=${SendGrid__FromEmail}
      - SendGrid__FromName=${SendGrid__FromName}
      - USE_REDIS=${USE_REDIS}
      - RabbitMq__HostName=${RabbitMq__HostName}
      - RabbitMq__UserName=${RabbitMq__UserName}
      - RabbitMq__Password=${RabbitMq__Password}
      - RabbitMq__VirtualHost=${RabbitMq__VirtualHost}
      - Supabase__AccessKeyID=${Access_key_ID}
      - Supabase__SecretAccessKey=${Secret_Access_key}
      - Supabase__EndPointS3=${EndPoint_S3}
    depends_on:
      redis:
        condition: service_started
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - greg-network
    volumes:
      - ../uploads:/app/wwwroot/uploads
      - ../logs:/app/logs

  frontend-portal:
    container_name: frontend-portal
    build:
      context: ../portal
      dockerfile: Dockerfile
      args:
        - VITE_GENERAL_BASEURL=${GENERAL__BASEURL}
    expose:
      - "80" # Fechado para fora, acessível apenas pelo Nginx internamente
    depends_on:
      - backend
    networks:
      - greg-network

  frontend-admin:
    container_name: frontend-admin
    build:
      context: ../admin
      dockerfile: Dockerfile
      args:
        - VITE_GENERAL_BASEURL=${GENERAL__BASEURL}
    expose:
      - "80" # Fechado para fora, acessível apenas pelo Nginx internamente
    depends_on:
      - backend
    networks:
      - greg-network

  ecommerce-bot:
    container_name: ecommerce-bot
    build: 
      context: ../ecommerce-bot
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=${MONGO_DATABASE_NAME}
      - MONGO_COLLECTION_NAME=${MONGO_COLLECTION_NAME}
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - greg-network

# --- [ NETWORKING & PERSISTENCE ] ---

networks:
  greg-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data: