kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: greg-company-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  # Mapeia a porta NodePort 30017 do cluster para a 27017 da sua máquina
  - containerPort: 30017
    hostPort: 27017
    protocol: TCP
  # Mapeia a porta NodePort 30379 do cluster para a 6379 da sua máquina
  - containerPort: 30379
    hostPort: 6379
    protocol: TCP
  # Mapeia a porta NodePort 30572 do cluster para a 5672 da sua máquina (RabbitMQ AMQP)
  - containerPort: 30572
    hostPort: 5672
    protocol: TCP
  # Mapeia a porta NodePort 31572 do cluster para a 15672 da sua máquina (RabbitMQ Management UI)
  - containerPort: 31572
    hostPort: 15672
    protocol: TCP
- role: worker