kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: greg-company-cluster
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 31543  # Porta customizada do Node (PostgreSQL)
    hostPort: 5432        # Porta física do seu PC local (Postgres)
    protocol: TCP
  - containerPort: 32379  # Porta customizada do Node (Redis)
    hostPort: 6379        # Porta física do seu PC local
    protocol: TCP
  - containerPort: 32017  # Porta customizada do Node (MongoDB)
    hostPort: 27017       # Porta física do seu PC local
    protocol: TCP