# Configurações globais do Nginx
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Otimizações de performance de rede
    sendfile        on;
    keepalive_timeout  65;

    # --- REGRA 1: TRÁFEGO DO PORTAL ---
    server {
        listen 80;
        server_name gregcompany.local; # URL que vamos usar no navegador

        location / {
            # O Nginx usa o DNS interno do Docker para achar o container pelo nome!
            proxy_pass http://frontend-portal:80; 
            
            # Repassa os cabeçalhos reais do usuário (essencial para segurança e logs)
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # --- REGRA 2: TRÁFEGO DO ADMIN ---
    server {
        listen 80;
        server_name admin.gregcompany.local; # Subdomínio para o painel de backoffice

        location / {
            proxy_pass http://frontend-admin:80;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # --- REGRA 3: TRÁFEGO DA API (.NET 8) ---
    server {
        listen 80;
        server_name api.gregcompany.local;

        location / {
            proxy_pass http://backend-api:8080; # Porta interna do container Kestrel do .NET
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Suporte a WebSockets (fundamental para os Hubs do SignalR e notificações)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}