apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greg-company-ingress
  namespace: greg-company
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # 🔥 INDISPENSÁVEL PARA SSE: Impede o Nginx de reter o chunked stream na memória
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  ingressClassName: nginx 
  rules:
  # --- REGRA 1: TRÁFEGO DO PORTAL ---
  - host: gregcompany.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal-service
            port:
              number: 8080 # Alinhado com a nova porta do Service

  # --- REGRA 2: TRÁFEGO DO ADMIN ---
  - host: admin.gregcompany.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-service
            port:
              number: 8080 # Alinhado com a nova porta do Service

  # --- REGRA 3: TRÁFEGO DA API & STREAM BOT ---
  - host: api.gregcompany.local
    http:
      paths:
      # Rota específica do Bot de IA (SSE Stream) interceptada primeiro
      - path: /api/v1/demo/stream
        pathType: Prefix
        backend:
          service:
            name: ecommerce-bot-service
            port:
              number: 8000
      # Rota genérica da API direcionada ao .NET 8
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-api-service
            port:
              number: 8080