apiVersion: v1
kind: ConfigMap
metadata:
  name: greg-configmap
  namespace: greg-company
data:
  ENVIRONMENT: "production"
  GENERAL__BASEURL: "https://api.gregcompany.com"
  USE_KUBERNETES_LOGS: "true"
  SCRAPER_BASE_URL: "https://exemplo-loja.com.br"
  Google__ClientId: "SEU_CLIENT_ID_AQUI"
  POSTGRES_DB_NAME: "greg_company"
  ConnectionStrings__Redis: "redis-service:6379"
  USE_REDIS: "TRUE"
  REDIS_URL: "redis://redis-service:6379"
  MercadoPago__PublicKey: "QVBQX1VTUi1hMjg1NjE0NC0yY2RlLTRjMGEtYjc2NC1kYWNhNWFiYjdjNjI="
  SendGrid__FromEmail: "lucasvicentedesouza021@gmail.com"
  SendGrid__FromName: "Greg Company"
  Access_key_ID: "1326cce953a33dd945a859ff9d1a6d82"
  EndPoint_S3: "https://bvoxyxmettvzaejhftrq.storage.supabase.co/storage/v1/s3"