apiVersion: v1
kind: ConfigMap
metadata:
  name: greg-configmap
  namespace: greg-company
data:
  ENVIRONMENT: "production"
  GENERAL__BASEURL: "https://api.gregcompany.com"
  VITE_GENERAL__BASEURL: "https://gregcompany.com"
  USE_KUBERNETES_LOGS: "true"
  CDN_BASE_URL: "https://api.gregcompany.com"
  Email_Admin: "lucasvicentedesouza021@gmail.com"
  Google__ClientId: "317826651619-a80lvh3utf0shuk1hut00inholqskp9a.apps.googleusercontent.com"
  POSTGRES_DB_NAME: "greg_company"
  ConnectionStrings__Redis: "redis-service:6379"
  USE_REDIS: "TRUE"
  REDIS_URL: "redis://redis-service:6379"
  MercadoPago__PublicKey: "APP_USR-a2856144-2cde-4c0a-b764-daca5abb7c62"
  SendGrid__FromEmail: "lucasvicentedesouza021@gmail.com"
  SendGrid__FromName: "Greg Company"
  Access_key_ID: "1326cce953a33dd945a859ff9d1a6d82"
  EndPoint_S3: "https://bvoxyxmettvzaejhftrq.storage.supabase.co/storage/v1/s3"