apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greg-company-ingress
  namespace: greg-company
  annotations:
    # O NGINX Ingress já ativa WebSockets por padrão, mas estas anotações 
    # otimizam os timeouts para o SignalR do .NET não cair a cada 60 segundos
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx 
  rules:
  # --- REGRA 1: TRÁFEGO DO PORTAL ---
  - host: gregcompany.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal-service # O Service que aponta para o teu Pod do Vite
            port:
              number: 80 # Porta exposta pelo Service interno

  # --- REGRA 2: TRÁFEGO DO ADMIN ---
  - host: admin.gregcompany.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-service # O Service do painel de administração
            port:
              number: 80

  # --- REGRA 3: TRÁFEGO DA API (.NET 8) ---
  - host: api.gregcompany.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-api-service # Substitui o "backend-api:8080" do teu conf
            port:
              number: 8080 # A porta em que a tua API .NET está a ouvir