apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: greg-company
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017
  selector:
    app: mongodb-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: greg-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-store
  template:
    metadata:
      labels:
        app: mongodb-store
    spec:
      containers:
        - name: mongodb-store
          image: mongo:7.0 # Versão fixa para paridade de ambiente
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          # emptyDir mantém os dados vivos mesmo se o contêiner falhar internamente.
          # Para produção real, substituiríamos por um PersistentVolumeClaim (PVC).
          emptyDir: {}