apiVersion: v1
kind: Namespace
metadata:
  name: greg-company
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: greg-company
spec:
  type: NodePort # <--- Adicionado
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32017 # <--- Bate com a containerPort do kind-config
  selector:
    app: mongodb-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: greg-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-store
  template:
    metadata:
      labels:
        app: mongodb-store
    spec:
      containers:
        - name: mongodb-store
          image: mongo:latest
          ports:
            - containerPort: 27017
