apiVersion: v1
kind: Namespace
metadata:
  name: greg-company
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: greg-company
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31543 # <--- Bate perfeitamente com a containerPort do kind-config
  selector:
    app: postgres-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: greg-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Opala@1704.Test!" # Mantida a senha padrão do teste local
            - name: POSTGRES_DB
              value: "greg_company"
          ports:
            - containerPort: 5432
