apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: greg-company
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30379
  selector:
    app: redis-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: greg-company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine # Imagem leve e previsível
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-persistent-storage
            mountPath: /data
      volumes:
        - name: redis-persistent-storage
          emptyDir: {}