name: CI/CD - Backend

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'backend/**'
      - 'Tests/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'backend/**'
      - 'Tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Criar arquivo .env para testes
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "ConnectionStrings__DefaultConnection=${{ secrets.DB_CONNECTION_STRING }}" >> .env
          echo "MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}" >> .env
          echo "ConnectionStrings__Redis=${{ secrets.REDIS_CONNECTION_STRING }}" >> .env
        working-directory: ./backend
      - name: Executar Testes
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from tests
        working-directory: ./backend

  build-and-push:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          # Transforma o nome do repo para minúsculas
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$REPO/backend
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} ./backend
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
